In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv("data/data_clean.csv")
df.head(1)

,Unnamed: 0,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09

In [17]:
df.describe()

,Unnamed: 0,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Views,Likes,Comments,Stream
count,20166.00000,20166.000000,20166.000000,20166.000000,20166.000000,20166.000000,20166.000000,20166.000000,20166.000000,20166.000000,20166.000000,2.016600e+04,2.016600e+04,2.009500e+04,2.006700e+04,1.961300e+04
mean,10371.20118,0.620110,0.635034,5.300853,-7.659951,0.096138,0.289069,0.055945,0.191380,0.529135,120.613849,2.248029e+05,9.386996e+07,6.624949e+05,2.752255e+04,1.372564e+08
std,5989.56573,0.165263,0.213788,3.577942,4.616296,0.110334,0.286047,0.193130,0.165329,0.245618,29.606136,1.257300e+05,2.748502e+08,1.788723e+06,1.935857e+05,2.463740e+08
min,0.00000,0.000000,0.000020,0.000000,-46.251000,0.000000,0.000001,0.000000,0.014500,0.000000,0.000000,3.098500e+04,0.000000e+00,0.000000e+00,0.000000e+00,6.574000e+03
25%,5175.25000,0.519000,0.508000,2.000000,-8.824000,0.035600,0.043900,0.000000,0.094000,0.339000,97.002000,1.802190e+05,1.813797e+06,2.149050e+04,5.075000e+02,1.780986e+07
50%,10380.50000,0.638000,0.666000,5.000000,-6.535000,0.050500,0.190000,0.000002,0.125000,0.536000,119.965000,2.133210e+05,1.446656e+07,1.242170e+05,3.263000e+03,4.980192e+07
75%,15567.75000,0.741000,0.797000,8.000000,-4.938000,0.103750,0.471000,0.000483,0.234000,0.726000,139.931750,2.522865e+05,7.030063e+07,5.217615e+05,1.436000e+04,1.395031e+08
max,20717.00000,0.975000,1.000000,11.000000,0.920000,0.964000,0.996000,1.000000,1.000000,0.993000,243.372000,4.676058e+06,8.079649e+09,5.078865e+07,1.608314e+07,3.386520e+09

In [18]:
from sklearn.preprocessing import StandardScaler

columns = [
    # 'Danceability',
    'Energy',
    'Speechiness',
    # 'Acousticness',
    # 'Instrumentalness',
    # 'Valence',
    # 'Tempo'
]
scaler = StandardScaler()
cleaned_df = pd.DataFrame(scaler.fit_transform(df[columns]), columns=columns)
cleaned_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19471 entries, 0 to 20165
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Energy       19471 non-null  float64
 1   Speechiness  19471 non-null  float64
dtypes: float64(2)
memory usage: 456.4 KB

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

index = 0
cos_sim = cosine_similarity(cleaned_df.iloc[[index]], cleaned_df)
best_index = np.argsort(cos_sim)[0][::-1][1:6]
best_index

array([  272, 14165, 14522,   415, 10652])

In [20]:
df.iloc[best_index].loc[:, columns]

       Energy  Speechiness
272     0.748       0.0323
14165   0.830       0.1060
14522   0.738       0.0292
415     0.820       0.2430
10652   0.807       0.0972

In [21]:
df.iloc[[index]].loc[:, columns]

   Energy  Speechiness
0   0.705        0.177